import os
import json
import datetime

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<title>RedScan Reconnaissance Report</title>
<style>
body {{
    background:#020617;
    color:#e5e7eb;
    font-family:Arial, Helvetica, sans-serif;
    line-height:1.7;
    margin:40px;
}}
h1 {{
    color:#38bdf8;
}}
h2 {{
    border-bottom:2px solid #1e293b;
    padding-bottom:6px;
    margin-top:35px;
}}
table {{
    border-collapse:collapse;
    width:100%;
    margin-top:12px;
}}
th, td {{
    border:1px solid #1e293b;
    padding:10px;
    font-size:14px;
}}
th {{
    color:#93c5fd;
}}
.section-note {{
    border-left:5px solid #38bdf8;
    padding:12px;
    color:#cbd5f5;
    margin-top:10px;
}}
.footer {{
    margin-top:40px;
    font-size:12px;
    color:#64748b;
    text-align:center;
}}
</style>
</head>

<body>

<h1>RedScan – Website Reconnaissance Report</h1>

<p>
This report contains publicly available technical information gathered during reconnaissance.
No exploitation or intrusive testing was performed.
</p>

<p><b>Target:</b> {target}</p>
<p><b>Generated:</b> {time}</p>

<hr>

{content}

<div class="footer">
Generated by RedScan – Modular Reconnaissance Framework
</div>

</body>
</html>
"""

# ---------------- HTML REPORT ---------------- #

def generate_html(target, content):
    base_dir = os.path.join("reports", target)
    os.makedirs(base_dir, exist_ok=True)

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(base_dir, f"recon_{timestamp}.html")

    html = HTML_TEMPLATE.format(
        target=target,
        time=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        content=content
    )

    with open(filename, "w", encoding="utf-8") as f:
        f.write(html)

    return filename

# ---------------- JSON REPORT ---------------- #

def generate_json(target, recon_data):
    base_dir = os.path.join("reports", target)
    os.makedirs(base_dir, exist_ok=True)

    filename = os.path.join(base_dir, "recon_latest.json")

    output = {
        "target": target,
        "generated_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "reconnaissance": recon_data
    }

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=4)

    return filename
